In [1]:
import pandas as pd
import numpy as np

In [141]:
# %matplotlib inline 

In [142]:
read_df = pd.read_csv('Fire_Incidents.tsv', sep='\t')

C:\Users\Rutul Thakkar\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3049: DtypeWarning: Columns (11,12,19,44,58) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
read_df.shape

(490557, 63)

In [4]:
read_df.describe()

Incident Number  Exposure Number   Call Number        Zipcode  \
count     4.905570e+05    490557.000000  4.905570e+05  417754.000000   
mean      1.075417e+07         0.000045  1.087612e+08   94113.480062   
std       4.701487e+06         0.009253  4.692795e+07      10.171593   
min       3.000001e+06         0.000000  3.001000e+07   94102.000000   
25%       7.021794e+06         0.000000  7.074036e+07   94105.000000   
50%       1.102821e+07         0.000000  1.108504e+08   94110.000000   
75%       1.504672e+07         0.000000  1.512323e+08   94121.000000   
max       1.903054e+07         5.000000  1.907200e+08   94158.000000   

       Suppression Units  Suppression Personnel      EMS Units  EMS Personnel  \
count      490557.000000          490557.000000  490557.000000  490557.000000   
mean            2.536606               9.125166       0.176071       0.326225   
std             8.918681              23.038565       0.784429       1.197361   
min             0.000000               0.000000       0.000000       0.000000   
25%             1.000000               4.000000       0.000000       0.000000   
50%             2.000000               9.000000       0.000000       0.000000   
75%             3.000000              10.000000       0.000000       0.000000   
max          3333.000000            5960.000000     150.000000     312.000000   

         Other Units  Other Personnel  ...  Civilian Fatalities  \
count  490557.000000    490557.000000  ...        490557.000000   
mean        0.034500         0.063151  ...             0.000061   
std         1.452718         1.522060  ...             0.009253   
min         0.000000         0.000000  ...             0.000000   
25%         0.000000         0.000000  ...             0.000000   
50%         0.000000         0.000000  ...             0.000000   
75%         0.000000         0.000000  ...             0.000000   
max      1000.000000      1000.000000  ...             3.000000   

       Civilian Injuries  Number of Alarms  Floor of Fire Origin  \
count      490557.000000               0.0           8143.000000   
mean            0.001164               NaN              2.276311   
std             0.065775               NaN              5.762561   
min             0.000000               NaN             -3.000000   
25%             0.000000               NaN              1.000000   
50%             0.000000               NaN              2.000000   
75%             0.000000               NaN              2.000000   
max            24.000000               NaN            105.000000   

       Number of floors with minimum damage  \
count                           6610.000000   
mean                               0.723298   
std                                0.510876   
min                                0.000000   
25%                                0.000000   
50%                                1.000000   
75%                                1.000000   
max                                5.000000   

       Number of floors with significant damage  \
count                               6599.000000   
mean                                   0.155781   
std                                    0.438704   
min                                    0.000000   
25%                                    0.000000   
50%                                    0.000000   
75%                                    0.000000   
max                                    7.000000   

       Number of floors with heavy damage  \
count                         6593.000000   
mean                             0.082967   
std                              0.339013   
min                              0.000000   
25%                              0.000000   
50%                              0.000000   
75%                              0.000000   
max                              5.000000   

       Number of floors with extreme damage  \
count                           6596.000000   
mean                       

In [5]:
read_df['Station Area'].unique()

array(['15', '39', '01', '10', '03', '16', '44', '40', '37', '35', '28',
       '33', '31', '07', '02', '38', '43', '17', '36', '06', '48', '12',
       '13', '23', '08', '20', 'A1', '41', '14', '29', '42', '21', '19',
       '11', '25', 'A3', '09', '26', '22', '34', '32', '18', '24', '05',
       'A2', '51', 'H1', nan, '53', '04', 'OT', 'A4', '99', '47', 1.0,
       5.0, 32.0, 7.0, 3.0, 13.0, 28.0, 35.0, 10.0, 11.0, 33.0, 31.0, 9.0,
       34.0, 41.0, 2.0, 29.0, 18.0, 20.0, 39.0, 21.0, 36.0, 8.0, 51.0,
       14.0, 24.0, 17.0, 26.0, 25.0, 15.0, 16.0, 37.0, 38.0, 44.0, 4.0,
       42.0, 12.0, 6.0, 43.0, 19.0, 22.0, 40.0, 48.0, 23.0, 47.0, 94.0],
      dtype=object)

In [6]:
 read_df.count()

Incident Number                                 490557
Exposure Number                                 490557
Address                                         490335
Incident Date                                   490557
Call Number                                     490557
Alarm DtTm                                      490557
Arrival DtTm                                    490524
Close DtTm                                      490556
City                                            489038
Zipcode                                         417754
Battalion                                       490557
Station Area                                    489750
Box                                             192727
Suppression Units                               490557
Suppression Personnel                           490557
EMS Units                                       490557
EMS Personnel                                   490557
Other Units                                     490557
Other Pers

In [7]:
read_df['Civilian Fatalities'].head(10)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
Name: Civilian Fatalities, dtype: int64

In [8]:
read_df['Civilian Fatalities'].unique()

array([0, 1, 2, 3], dtype=int64)

In [9]:
read_df['Civilian Injuries'].head(10)

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
Name: Civilian Injuries, dtype: int64

In [10]:
read_df['Civilian Injuries'].unique()

array([ 0,  1,  2,  3,  4,  8,  9,  6,  5,  7, 24, 10], dtype=int64)

In [11]:
read_df['Mutual Aid'].head(10)

0      none
1      none
2      none
3      none
4      none
5      none
6      none
7    n none
8      none
9      none
Name: Mutual Aid, dtype: object

In [12]:
read_df['Mutual Aid'].count()

490557

In [13]:
 read_df.count()

Incident Number                                 490557
Exposure Number                                 490557
Address                                         490335
Incident Date                                   490557
Call Number                                     490557
Alarm DtTm                                      490557
Arrival DtTm                                    490524
Close DtTm                                      490556
City                                            489038
Zipcode                                         417754
Battalion                                       490557
Station Area                                    489750
Box                                             192727
Suppression Units                               490557
Suppression Personnel                           490557
EMS Units                                       490557
EMS Personnel                                   490557
Other Units                                     490557
Other Pers

In [14]:
read_df.describe()

Incident Number  Exposure Number   Call Number        Zipcode  \
count     4.905570e+05    490557.000000  4.905570e+05  417754.000000   
mean      1.075417e+07         0.000045  1.087612e+08   94113.480062   
std       4.701487e+06         0.009253  4.692795e+07      10.171593   
min       3.000001e+06         0.000000  3.001000e+07   94102.000000   
25%       7.021794e+06         0.000000  7.074036e+07   94105.000000   
50%       1.102821e+07         0.000000  1.108504e+08   94110.000000   
75%       1.504672e+07         0.000000  1.512323e+08   94121.000000   
max       1.903054e+07         5.000000  1.907200e+08   94158.000000   

       Suppression Units  Suppression Personnel      EMS Units  EMS Personnel  \
count      490557.000000          490557.000000  490557.000000  490557.000000   
mean            2.536606               9.125166       0.176071       0.326225   
std             8.918681              23.038565       0.784429       1.197361   
min             0.000000               0.000000       0.000000       0.000000   
25%             1.000000               4.000000       0.000000       0.000000   
50%             2.000000               9.000000       0.000000       0.000000   
75%             3.000000              10.000000       0.000000       0.000000   
max          3333.000000            5960.000000     150.000000     312.000000   

         Other Units  Other Personnel  ...  Civilian Fatalities  \
count  490557.000000    490557.000000  ...        490557.000000   
mean        0.034500         0.063151  ...             0.000061   
std         1.452718         1.522060  ...             0.009253   
min         0.000000         0.000000  ...             0.000000   
25%         0.000000         0.000000  ...             0.000000   
50%         0.000000         0.000000  ...             0.000000   
75%         0.000000         0.000000  ...             0.000000   
max      1000.000000      1000.000000  ...             3.000000   

       Civilian Injuries  Number of Alarms  Floor of Fire Origin  \
count      490557.000000               0.0           8143.000000   
mean            0.001164               NaN              2.276311   
std             0.065775               NaN              5.762561   
min             0.000000               NaN             -3.000000   
25%             0.000000               NaN              1.000000   
50%             0.000000               NaN              2.000000   
75%             0.000000               NaN              2.000000   
max            24.000000               NaN            105.000000   

       Number of floors with minimum damage  \
count                           6610.000000   
mean                               0.723298   
std                                0.510876   
min                                0.000000   
25%                                0.000000   
50%                                1.000000   
75%                                1.000000   
max                                5.000000   

       Number of floors with significant damage  \
count                               6599.000000   
mean                                   0.155781   
std                                    0.438704   
min                                    0.000000   
25%                                    0.000000   
50%                                    0.000000   
75%                                    0.000000   
max                                    7.000000   

       Number of floors with heavy damage  \
count                         6593.000000   
mean                             0.082967   
std                              0.339013   
min                              0.000000   
25%                              0.000000   
50%                              0.000000   
75%                              0.000000   
max                              5.000000   

       Number of floors with extreme damage  \
count                           6596.000000   
mean                       

In [15]:
read_df['Zipcode'].unique()

array([   nan, 94103., 94109., 94123., 94134., 94122., 94107., 94118.,
       94105., 94133., 94127., 94110., 94108., 94112., 94102., 94124.,
       94130., 94115., 94131., 94114., 94111., 94117., 94104., 94132.,
       94116., 94121., 94158., 94129.])

In [16]:
# read_df['Zipcode'].isna().sum()

In [17]:
# read_df['Zipcode'] = read_df['Zipcode'].dropna()

In [18]:
read_df.shape

(490557, 63)

In [19]:
read_df

Incident Number  Exposure Number                       Address  \
0               9030109                0                 310 Colon Av.   
1              13067402                0                20 Lansdale Av   
2              12044490                0          7th St. / Folsom St.   
3              13033326                0               2799 Pacific Av   
4              11101416                0           Polk St. / Pine St.   
5              12077793                0                2824 Scott St.   
6               7021713                0     San Bruno Av. / Teddy Av.   
7              15065212                0           1532 Noriega Street   
8              10097225                0             1215 Carolina St.   
9               8033299                0                870 Kansas St.   
10              8098069                0           3700 California St.   
11              5008050                0                 101 Spear St.   
12              4012483                0      Columbus Av. / Union St.   
13             13110544                0               150 Dalewood Wy   
14              5049481                0             253 Castenada Av.   
15              3091192                0              203 Plymouth Av.   
16              5002244                0                  645 14th Av.   
17              3048160                0              567 Shotwell St.   
18              4033909                0    Mason St. / Washington St.   
19              3031831                0              3325 Steiner St.   
20              6060988                0                   125 6th St.   
21              5006655                0             1080 Chestnut St.   
22             11051320                0    Wilde Av. / Goettingen St.   
23              7023372                0             1801 Franklin St.   
24              8004011                0    Naples St. / Excelsior Av.   
25              3057101                0  Golden Gate Av. / Larkin St.   
26              3066990                0             650 Jamestown Av.   
27             12060923                0         Taylor St. / Eddy St.   
28             12099458                0             1325 Chestnut St.   
29             10031787                0              190 Ofarrell St.   
...                 ...              ...                           ...   
490527         19030222                0          405 Serrano Dr 4thfl   
490528         19030234                0           1301 Sansome Street   
490529         19030247                0                 211 30th St 8   
490530         19030248                0       405 Serrano Dr 9j Drive   
490531         19030250                0           962 Ingerson Avenue   
490532         19030286                0           345 Williams Avenue   
490533         19030297                0                Precita Avenue   
490534         19030351                0          1 101nb Bayshore 3rd   
490535         19030372                0        427 Connecticut Street   
490536         19030374                0             Junipero Serra Bl   
490537         19030398                0            1845 Powell Street   
490538         19030410                0        350 Golden Gate Avenue   
490539         19030412                0        100 Blk Beverly Street   
490540         19030418                0             149 Oxford Street   
490541         19030422                0            24 Wentworth Place   
490542         19030423                0                    Skyline Bl   
490543         19030425                0                201 8th Street   
490544         19030430                0                   Turk Street   
490545         19030436                0              Coleridge Street   
490546         19030442                0            680 Mission Street   
490547         19030457                0            55 Chumasero Drive   
490548         19030459                0             1450 Post St 1001   
490549      

In [20]:
df_X = read_df.drop(['Number of Alarms', 'Number of floors with minimum damage', 'Number of floors with significant damage', 'Ignition Cause', 'Number of floors with heavy damage', 'Number of floors with extreme damage', 'Detector Failure Reason', 'Number of Sprinkler Heads Operating', 'Item First Ignited', 'Automatic Extinguishing Sytem Type', 'Automatic Extinguishing Sytem Perfomance', 'Automatic Extinguishing Sytem Failure Reason', 'Supervisor District', 'Neighborhood  District'  ], axis = 1)

In [21]:
df_X.describe()

Incident Number  Exposure Number   Call Number        Zipcode  \
count     4.905570e+05    490557.000000  4.905570e+05  417754.000000   
mean      1.075417e+07         0.000045  1.087612e+08   94113.480062   
std       4.701487e+06         0.009253  4.692795e+07      10.171593   
min       3.000001e+06         0.000000  3.001000e+07   94102.000000   
25%       7.021794e+06         0.000000  7.074036e+07   94105.000000   
50%       1.102821e+07         0.000000  1.108504e+08   94110.000000   
75%       1.504672e+07         0.000000  1.512323e+08   94121.000000   
max       1.903054e+07         5.000000  1.907200e+08   94158.000000   

       Suppression Units  Suppression Personnel      EMS Units  EMS Personnel  \
count      490557.000000          490557.000000  490557.000000  490557.000000   
mean            2.536606               9.125166       0.176071       0.326225   
std             8.918681              23.038565       0.784429       1.197361   
min             0.000000               0.000000       0.000000       0.000000   
25%             1.000000               4.000000       0.000000       0.000000   
50%             2.000000               9.000000       0.000000       0.000000   
75%             3.000000              10.000000       0.000000       0.000000   
max          3333.000000            5960.000000     150.000000     312.000000   

         Other Units  Other Personnel  Estimated Property Loss  \
count  490557.000000    490557.000000             1.283990e+05   
mean        0.034500         0.063151             4.927927e+03   
std         1.452718         1.522060             3.122298e+05   
min         0.000000         0.000000            -2.500000e+04   
25%         0.000000         0.000000             0.000000e+00   
50%         0.000000         0.000000             0.000000e+00   
75%         0.000000         0.000000             0.000000e+00   
max      1000.000000      1000.000000             1.000000e+08   

       Estimated Contents Loss  Fire Fatalities  Fire Injuries  \
count             1.355060e+05    490557.000000  490557.000000   
mean              1.906946e+03         0.000004       0.000300   
std               2.755932e+05         0.002856       0.025974   
min              -5.000000e+03         0.000000       0.000000   
25%               0.000000e+00         0.000000       0.000000   
50%               0.000000e+00         0.000000       0.000000   
75%               0.000000e+00         0.000000       0.000000   
max               1.000000e+08         2.000000       9.000000   

       Civilian Fatalities  Civilian Injuries  Floor of Fire Origin  
count        490557.000000      490557.000000           8143.000000  
mean              0.000061           0.001164              2.276311  
std               0.009253           0.065775              5.762561  
min               0.000000           0.000000             -3.000000  
25%               0.000000           0.000000              1.000000  
50%               0.000000           0.000000              2.000000  
75%               0.000000           0.000000              2.000000  
max               3.000000          24.000000            105.000000

In [22]:
df_X['Detector Operation'].unique()

array([nan, '2 -detector operated', '-', '3 -detector failed to operate',
       '2 detector operated', '1 -fire too small to activate detector',
       'u -undetermined', '1 fire too small to activate detector',
       'u undetermined', '3 detector failed to operate'], dtype=object)

In [23]:
df_X['First Unit On Scene'].unique()

array(['T15', 'E39', 'B03', 'B04', 'E03', 'E51', 'E42', nan, 'E37', 'E10',
       'E15', 'E28', 'B07', 'T07', 'E02', 'E16', 'RS1', 'T17', 'E43',
       'E17', 'E01', 'T01', 'E36', 'E06', 'E48', 'E38', 'E12', 'E44',
       '89', 'T03', 'T13', 'E23', 'E31', '68', 'E20', 'M10', '63', 'E13',
       'AP', 'E41', '57', 'T14', 'E07', 'E29', 'E08', 'E05', 'E33', 'E21',
       'E09', 'E19', 'E11', 'B06', '88', 'B02', 'T18', 'T06', 'E35',
       'E14', '92', 'RS2', 'M17', 'T11', '93', 'E25', 'T10', 'E26', 'T19',
       'E22', 'E34', 'E32', 'T09', 'T16', 'M36', 'E18', '85', 'T05',
       'E40', 'T08', 'B01', '67', 'T02', 'D3', 'B10', 'B08', 'T12', 'RC3',
       'B09', 'M05', 'E24', '86', '74', 'RC2', 'M14', 'D2', '65', '94',
       '79', '96', 'T48', '95', '66', '81', '84', '91', 'RC1', '64', '72',
       'M29', 'M28', 'E47', '71', '54', '87', 'M18', '75', '82', 'RA48',
       'M22', 'M19', '76', 'M43', 'M32', '77', '59', 'M03', '83', '55',
       'OTH', 'M15', '78', 'HT48', 'SR1', 'M38', 'M09', 

In [24]:
df_X['Action Taken Secondary'].unique()

array(['-', nan, '86 - investigate', '12 - salvage & overhaul',
       '33 - provide advanced life support (als)',
       '82 - notify other agencies.', '34 - transport person',
       '70 - assistance, other', '51 - ventilate', '66 - remove water',
       '31 - provide first aid & check for injuries',
       '65 - secure property', '87 - investigate - fire out on arrival',
       '63 - restore fire alarm system',
       '42 - hazmat detect/monitor/sampling & analysis',
       '47 - decontaminate occupancy or area',
       '11 extinguishment by fire service personnel',
       '52 - forcible entry', '85 - enforce code',
       '40 - hazardous condition, other', '73 - provide manpower',
       '71 - assist physically disabled', '51 ventilate',
       '12 salvage & overhaul', '64 shut down system',
       '64 - shut down system', '81 - incident command',
       '11 - extinguish', '78 - control traffic',
       '55 - establish safe area', '92 - standby',
       '63 restore fire alarm syste

In [25]:
df_X.count()

Incident Number                           490557
Exposure Number                           490557
Address                                   490335
Incident Date                             490557
Call Number                               490557
Alarm DtTm                                490557
Arrival DtTm                              490524
Close DtTm                                490556
City                                      489038
Zipcode                                   417754
Battalion                                 490557
Station Area                              489750
Box                                       192727
Suppression Units                         490557
Suppression Personnel                     490557
EMS Units                                 490557
EMS Personnel                             490557
Other Units                               490557
Other Personnel                           490557
First Unit On Scene                       329809
Estimated Property L

In [26]:
df_X.shape

(490557, 49)

In [27]:
df_X['Fire Spread'].unique()

array([nan, '-', '20 -furniture, utensils, other',
       '25 -appliance housing or casing', '00 -item first ignited, other',
       '12 -exterior wall covering or finish',
       '10 -structural component or finish, other',
       '14 -floor covering or rug/carpet/mat',
       '17 -structural member or framing',
       '81 -electrical wire, cable insulation',
       '32 -bedding; blanket, sheet, comforter',
       '23 -cabinetry (including built-in)', '31 -mattress, pillow',
       '96 -rubbish, trash, or waste', '97 -oily rags',
       '76 -cooking materials, inc. edible materia',
       '34 -wearing apparel not on a person',
       '11 -exterior roof covering or finish',
       '15 -int. wall cover  exclude drapes, etc.',
       '16 -interior ceiling covering or finish', 'uu -undetermined',
       '70 -organic materials, other',
       '18 -insulation within structural area',
       '92 -magazine, newspaper, writing paper',
       '13 -exterior trim, including doors',
       '33 -li

In [28]:
df_X['Primary Situation'].unique()

array(['551 - assist pd or other govern. agency',
       '745 - alarm system sounded/no fire-accidental',
       '711 - municipal alarm system, street box false',
       '746 - co detector activation, no co',
       '700 - false alarm or false call, other',
       '113 cooking fire, confined to container',
       '550 - public service assistance, other',
       '735 - alarm system sounded due to malfunction',
       '710 - malicious, mischievous false call, other',
       '500 - service call, other', '522 - water or steam leak',
       '111 - building fire',
       '744 - detector activation, no fire - accident',
       '323 - auto/ped. accident (veh.)', '600 - good intent call, other',
       '736 - co detector activation/malfunction',
       '730 - system malfunction, other', '554 - assist invalid',
       '440 - elec. wiring/equip. problem, other',
       '900 - special type of incident, other',
       '463 - vehicle accident, general cleanup',
       '911 - citizen complaint',
    

In [29]:
df_X['Action Taken Other'].unique()

array(['-', nan, '86 - investigate',
       '83 - provide information to public/media', '51 - ventilate',
       '63 - restore fire alarm system', '52 - forcible entry',
       '70 - assistance, other', '85 - enforce code',
       '34 - transport person', '71 - assist physically disabled',
       '78 - control traffic', '72 - assist animal',
       '84 - refer to proper authority', '12 salvage & overhaul',
       '81 - incident command', '87 - investigate - fire out on arrival',
       '92 - standby', '33 - provide advanced life support (als)',
       '82 - notify other agencies.',
       '32 - provide basic life support (bls)', '45 - remove hazard',
       '55 - establish safe area', '66 - remove water',
       '65 - secure property', '64 - shut down system',
       '20 search & rescue, other', '86 investigate',
       '23 extricate, disentangle', '15 - confine fire (wildland)',
       '62 - restore fire protection system',
       '31 - provide first aid & check for injuries', '21 - s

In [30]:
df_X1 = df_X.drop(['Human Factors Associated with Ignition','Arrival DtTm', 'Close DtTm', 'No Flame Spead', 'Mutual Aid','City','Fire Spread','Detector Type','Detector Operation','Detector Effectiveness', 'Primary Situation', 'Other Units'
 ,'Other Personnel', 'Action Taken Other', 'Action Taken Secondary', 'First Unit On Scene', 'Call Number','Station Area' ], axis=1)

In [31]:
df_X1['Action Taken Primary'].head(10)

0    52 - forcible entry
1       86 - investigate
2       86 - investigate
3       86 - investigate
4       86 - investigate
5       86 - investigate
6       86 - investigate
7      52 forcible entry
8       86 - investigate
9       86 - investigate
Name: Action Taken Primary, dtype: object

In [32]:
df_X1['Structure Status'].unique()

array([nan, '2 -in normal use', '-', '3 -idle, not routinely used',
       '5 -vacant and secured', '2 in normal use',
       '6 -vacant and unsecured', '0 -other', '1 -under construction',
       '4 -under major renovation', '1 under construction',
       '4 under major renovation', 'u -undetermined',
       '7 -being demolished', 'u undetermined', '5 vacant and secured',
       '0 building status, other', '6 vacant and unsecured',
       '3 idle, not routinely used', '7 being demolished'], dtype=object)

In [33]:
df_X1['Structure Type'].unique()

array([nan, '1 -enclosed building', '3 -open structure', '-',
       '2 -fixed portable or mobile structure', '1 enclosed building',
       '0 -structure type, other', '5 -tent', '6 -open platform',
       '7 -underground structure work areas', '8 -connective structure',
       '0 structure type, other', '4 -air supported structure',
       '3 open structure', '6 open platform', '8 connective structure',
       '2 fixed portable or mobile structure',
       '7 underground structure work area', '4 air-supported structure',
       '5 tent'], dtype=object)

In [34]:
df_X1['Floor of Fire Origin'].unique()

array([ nan,   3.,   0.,   1.,   2.,   5.,   4.,   7.,  11.,  10.,  25.,
        12.,   8.,   6.,  15.,  14., 102.,   9.,  17.,  -3.,  -1.,  44.,
       104.,  19.,  13.,  18.,  30.,  22., 103.,  23.,  24.,  37.,  27.,
        29., 101.,  16.,  38.,  26.,  20., 105.,  -2.,  34.,  32.])

In [35]:
df_X1['Automatic Extinguishing System Present'].unique()

array([nan, 'n -none present', '-', '1 -present', 'u -undetermined',
       'n none present', '1 present', 'u undetermined',
       '2 -partial system present', '2 partial system present'],
      dtype=object)

In [36]:
df_X1.shape

(490557, 31)

In [37]:
df_X1['Area of Fire Origin'].unique()
#df_aor = df_X1[df_X1['Area of Fire Origin'] == 'nan']


array([nan, '21 - bedroom-<5 persons; inc. jail or pris',
       '40 - storage area, other', '24 - cooking area, kitchen',
       '43 - storage: supplies or tools; dead stor',
       '14 - common room, den, family/living room',
       '72 - exterior balcony, unenclosed porch', '-',
       '81 - operator/passenger area/transport equ',
       '83 - engine area, running gear, wheel area',
       '95 - wildland, woods', '74 - attic: vacant, crawl space',
       '00 - other', '70 - structural area, other', '97 - multiple areas',
       '22 - bedroom-5+persons; inc. barrack/dorms',
       '80 - vehicle area, other', 'uu - undetermined',
       '92 - highway, parking lot, street: on or n',
       '77 - roof surface: exterior', '90 - outside area, other',
       '41 - storage room, area, tank, or bin',
       '94 - open area - outside; inc. are farmlan',
       '26 - laundry area, wash house (laundry)',
       '60 - equipment or service area, other',
       '14 common room, den, family room, l

In [38]:
df_X1['Box'].unique()

array([nan, 8571.0, 4163.0, ..., 743, 733, 968], dtype=object)

In [149]:
# # Visualisation
# import matplotlib as mpl
# import matplotlib.pyplot as plt
# import matplotlib.pylab as pylab
# import seaborn as sns

# # Configure visualisations
# %matplotlib inline
# mpl.style.use( 'ggplot' )
# sns.set_style( 'white' )
# pylab.rcParams[ 'figure.figsize' ] = 10, 8

# def plot_correlation_map( df ):
#     corr = df.corr()
#     _ , ax = plt.subplots( figsize =( 20 , 20 ) )
#     cmap = sns.diverging_palette( 220 , 10 , as_cmap = True )
#     _ = sns.heatmap(
#         corr, 
#         cmap = cmap,
#         square=True, 
#         cbar_kws={ 'shrink' : .9 }, 
#         ax=ax, 
#         annot = True, 
#         annot_kws = { 'fontsize' : 8 }
#     )

In [150]:
#plot_correlation_map(df_X1)

In [145]:
df_X1.shape

(490557, 34)

In [146]:
df_X1.head(10)

Incident Number  Exposure Number                    Address Incident Date  \
0          9030109                0              310 Colon Av.    04/12/2009   
1         13067402                0             20 Lansdale Av    07/18/2013   
2         12044490                0       7th St. / Folsom St.    05/13/2012   
3         13033326                0            2799 Pacific Av    04/09/2013   
4         11101416                0        Polk St. / Pine St.    11/01/2011   
5         12077793                0             2824 Scott St.    08/22/2012   
6          7021713                0  San Bruno Av. / Teddy Av.    03/15/2007   
7         15065212                0        1532 Noriega Street    06/20/2015   
8         10097225                0          1215 Carolina St.    10/31/2010   
9          8033299                0             870 Kansas St.    04/17/2008   

               Alarm DtTm  Zipcode Battalion   Box  Suppression Units  \
0  04/12/2009 06:09:13 PM      NaN       B09   NaN                  1   
1  07/18/2013 10:32:03 AM      NaN       B09  8571                  3   
2  05/13/2012 03:55:37 AM  94103.0       B03   NaN                  3   
3  04/09/2013 04:34:07 PM      NaN       B04  4163                  3   
4  11/01/2011 06:07:45 PM  94109.0       B04   NaN                  2   
5  08/22/2012 08:58:06 AM  94123.0       B04   NaN                  3   
6  03/15/2007 01:55:35 PM  94134.0       B10   NaN                  1   
7  06/20/2015 02:44:56 AM  94122.0       B08  7431                  8   
8  10/31/2010 05:14:49 PM  94107.0       B10   NaN                  3   
9  04/17/2008 05:54:33 PM  94107.0       B10   NaN                  1   

   Suppression Personnel  ...  Heat Source  Structure Type  Structure Status  \
0                      5  ...          NaN             NaN               NaN   
1                     11  ...          NaN             NaN               NaN   
2                     10  ...          NaN             NaN               NaN   
3                     10  ...          NaN             NaN               NaN   
4                      9  ...          NaN             NaN               NaN   
5                     11  ...          NaN             NaN               NaN   
6                      4  ...          NaN             NaN               NaN   
7                     28  ...          NaN             NaN               NaN   
8                     10  ...          NaN             NaN               NaN   
9                      4  ...          NaN             NaN               NaN   

   Floor of Fire Origin  Detectors Present  \
0                   NaN                NaN   
1                   NaN                NaN   
2                   NaN                NaN   
3                   NaN                NaN   
4                   NaN                NaN   
5                   NaN                NaN   
6                   NaN                NaN   
7                   NaN                NaN   
8                   NaN                NaN   
9                   NaN                NaN   

   Automatic Extinguishing System Present                           Location  \
0                                     NaN                                NaN   
1                                     NaN                                NaN   
2                                     NaN    (37.7767460000297, -122.407844)   
3                                     NaN                                NaN   
4                                     NaN    (37.7896190000297, -122.420497)   
5                                     NaN  (37.7960234800297, -122.43998326)   
6                                     NaN      (37.7129950000296, -122.4021)   
7                                     NaN    (37.7541490000296, -122.480073)   
8                                     NaN    (37.7533230000297, -122.399403)   
9                                     NaN  (37.7585613300297, -122.40325885)   

   Weekday Hour Month  
0        6   18     4  
1

In [147]:
# plot_correlation_map(read_df)

In [44]:
from datetime import datetime

def convert_date_to_weekday(tmstp):
    result = datetime.strptime(tmstp, '%m/%d/%Y %I:%M:%S %p').weekday()
    return result
    
def convert_date_to_hour(tmstp):
    result = datetime.strptime(tmstp, '%m/%d/%Y %I:%M:%S %p').hour
    return result

def convert_date_to_month(tmstp):
    result = datetime.strptime(tmstp, '%m/%d/%Y %I:%M:%S %p').month
    return result

In [45]:
df_X1['Weekday'] = df_X1['Alarm DtTm'].apply(lambda x: convert_date_to_weekday(x))

In [46]:
df_X1['Hour'] = df_X1['Alarm DtTm'].apply(lambda x: convert_date_to_hour(x))

In [47]:
df_X1['Month'] = df_X1['Alarm DtTm'].apply(lambda x: convert_date_to_month(x))

In [48]:
df_X2 = df_X1.drop(['Exposure Number','Location', 'Ignition Factor Secondary', 'Heat Source','Floor of Fire Origin','Box' ,'Structure Status','Alarm DtTm', 'Area of Fire Origin', 'Incident Date', 'Incident Number', 'Action Taken Primary','Ignition Factor Primary', 'Structure Type', 'Automatic Extinguishing System Present','Detectors Present','Property Use','Estimated Property Loss','Estimated Contents Loss', 'Detector Alerted Occupants', 'Address'], axis=1)

In [49]:
df_X2.head(10)

Zipcode Battalion  Suppression Units  Suppression Personnel  EMS Units  \
0      NaN       B09                  1                      5          0   
1      NaN       B09                  3                     11          0   
2  94103.0       B03                  3                     10          0   
3      NaN       B04                  3                     10          0   
4  94109.0       B04                  2                      9          0   
5  94123.0       B04                  3                     11          0   
6  94134.0       B10                  1                      4          0   
7  94122.0       B08                  8                     28          1   
8  94107.0       B10                  3                     10          0   
9  94107.0       B10                  1                      4          0   

   EMS Personnel  Fire Fatalities  Fire Injuries  Civilian Fatalities  \
0              0                0              0                    0   
1              0                0              0                    0   
2              0                0              0                    0   
3              0                0              0                    0   
4              0                0              0                    0   
5              0                0              0                    0   
6              0                0              0                    0   
7              2                0              0                    0   
8              0                0              0                    0   
9              0                0              0                    0   

   Civilian Injuries  Weekday  Hour  Month  
0                  0        6    18      4  
1                  0        3    10      7  
2                  0        6     3      5  
3                  0        1    16      4  
4                  0        1    18     11  
5                  0        2     8      8  
6                  0        3    13      3  
7                  0        5     2      6  
8                  0        6    17     10  
9                  0        3    17      4

In [50]:
list(df_X2)

['Zipcode',
 'Battalion',
 'Suppression Units',
 'Suppression Personnel',
 'EMS Units',
 'EMS Personnel',
 'Fire Fatalities',
 'Fire Injuries',
 'Civilian Fatalities',
 'Civilian Injuries',
 'Weekday',
 'Hour',
 'Month']

In [148]:
# plot_correlation_map(df_X2)

In [52]:
df_X1['Area of Fire Origin'].unique()

array([nan, '21 - bedroom-<5 persons; inc. jail or pris',
       '40 - storage area, other', '24 - cooking area, kitchen',
       '43 - storage: supplies or tools; dead stor',
       '14 - common room, den, family/living room',
       '72 - exterior balcony, unenclosed porch', '-',
       '81 - operator/passenger area/transport equ',
       '83 - engine area, running gear, wheel area',
       '95 - wildland, woods', '74 - attic: vacant, crawl space',
       '00 - other', '70 - structural area, other', '97 - multiple areas',
       '22 - bedroom-5+persons; inc. barrack/dorms',
       '80 - vehicle area, other', 'uu - undetermined',
       '92 - highway, parking lot, street: on or n',
       '77 - roof surface: exterior', '90 - outside area, other',
       '41 - storage room, area, tank, or bin',
       '94 - open area - outside; inc. are farmlan',
       '26 - laundry area, wash house (laundry)',
       '60 - equipment or service area, other',
       '14 common room, den, family room, l

In [53]:
df_X1['Detector Alerted Occupants'].unique()

array(['-', '2 detector did not alert occupants',
       '1 - detector alerted occupants', 'u - unknown',
       '2 - detector did not alert occupants', nan,
       '1 detector alerted occupants', 'u unknown'], dtype=object)

In [54]:
df_X1['Property Use'].unique()

array(['000 - property use, other', '429 - multifamily dwellings',
       '963 - street or road in commercial area',
       '419 - 1 or 2 family dwelling', '960 - street, other',
       '400 - residential, other',
       '962 - residential street, road or residential dr',
       '161 restaurant or cafeteria', '500 - mercantile, business, other',
       '331 - hospital - medical or psychiatric', 'uuu - undetermined',
       '215 - middle/junior or high school',
       '110 - fixed use recreation places, other',
       '965 - vehicle parking area', '449 - hotel/motel, commercial',
       '439 - boarding/rooming house, res. hotels',
       '122 - convention center, exhibition hall',
       '899 - residential or self storage units',
       '807 - outside material storage area',
       '961 - highway or divided highway (street)',
       '171 - airport passenger terminal',
       '900 - outside or special property, other',
       '100 - assembly, other', '211 - preschool', '-',
       '161 -

In [55]:
df_X1['Structure Type'].unique()

array([nan, '1 -enclosed building', '3 -open structure', '-',
       '2 -fixed portable or mobile structure', '1 enclosed building',
       '0 -structure type, other', '5 -tent', '6 -open platform',
       '7 -underground structure work areas', '8 -connective structure',
       '0 structure type, other', '4 -air supported structure',
       '3 open structure', '6 open platform', '8 connective structure',
       '2 fixed portable or mobile structure',
       '7 underground structure work area', '4 air-supported structure',
       '5 tent'], dtype=object)

In [56]:
df_X1['Structure Status'].unique()

array([nan, '2 -in normal use', '-', '3 -idle, not routinely used',
       '5 -vacant and secured', '2 in normal use',
       '6 -vacant and unsecured', '0 -other', '1 -under construction',
       '4 -under major renovation', '1 under construction',
       '4 under major renovation', 'u -undetermined',
       '7 -being demolished', 'u undetermined', '5 vacant and secured',
       '0 building status, other', '6 vacant and unsecured',
       '3 idle, not routinely used', '7 being demolished'], dtype=object)

In [57]:
df_X1['Structure Status'].value_counts()

2 -in normal use               5239
-                              3826
2 in normal use                1459
5 -vacant and secured           145
1 -under construction            90
6 -vacant and unsecured          89
4 -under major renovation        80
3 -idle, not routinely used      59
1 under construction             56
0 -other                         38
5 vacant and secured             20
6 vacant and unsecured           16
4 under major renovation         16
u -undetermined                   8
3 idle, not routinely used        7
u undetermined                    6
0 building status, other          6
7 -being demolished               3
7 being demolished                3
Name: Structure Status, dtype: int64

In [58]:
df_X1['Structure Type'].value_counts()

1 -enclosed building                     5523
-                                        3011
1 enclosed building                      1513
0 -structure type, other                  361
3 -open structure                         272
5 -tent                                   159
2 -fixed portable or mobile structure     108
0 structure type, other                    97
6 -open platform                           71
8 -connective structure                    43
3 open structure                           37
2 fixed portable or mobile structure       32
7 -underground structure work areas        27
8 connective structure                      9
6 open platform                             8
5 tent                                      5
4 -air supported structure                  2
7 underground structure work area           2
4 air-supported structure                   1
Name: Structure Type, dtype: int64

#### Needed in preprocessing to train the model, not needed to test it

df_X2 = df_X2.drop_duplicates()

In [60]:

#df_X2 = df_X2.dropna()

In [61]:
df_X2.head(10)

Zipcode Battalion  Suppression Units  Suppression Personnel  EMS Units  \
0      NaN       B09                  1                      5          0   
1      NaN       B09                  3                     11          0   
2  94103.0       B03                  3                     10          0   
3      NaN       B04                  3                     10          0   
4  94109.0       B04                  2                      9          0   
5  94123.0       B04                  3                     11          0   
6  94134.0       B10                  1                      4          0   
7  94122.0       B08                  8                     28          1   
8  94107.0       B10                  3                     10          0   
9  94107.0       B10                  1                      4          0   

   EMS Personnel  Fire Fatalities  Fire Injuries  Civilian Fatalities  \
0              0                0              0                    0   
1              0                0              0                    0   
2              0                0              0                    0   
3              0                0              0                    0   
4              0                0              0                    0   
5              0                0              0                    0   
6              0                0              0                    0   
7              2                0              0                    0   
8              0                0              0                    0   
9              0                0              0                    0   

   Civilian Injuries  Weekday  Hour  Month  
0                  0        6    18      4  
1                  0        3    10      7  
2                  0        6     3      5  
3                  0        1    16      4  
4                  0        1    18     11  
5                  0        2     8      8  
6                  0        3    13      3  
7                  0        5     2      6  
8                  0        6    17     10  
9                  0        3    17      4

In [62]:
df_X2.shape

(318506, 13)

In [63]:
df_X2.count()

Zipcode                  266535
Battalion                318506
Suppression Units        318506
Suppression Personnel    318506
EMS Units                318506
EMS Personnel            318506
Fire Fatalities          318506
Fire Injuries            318506
Civilian Fatalities      318506
Civilian Injuries        318506
Weekday                  318506
Hour                     318506
Month                    318506
dtype: int64

In [64]:
df_X2.head()

Zipcode Battalion  Suppression Units  Suppression Personnel  EMS Units  \
0      NaN       B09                  1                      5          0   
1      NaN       B09                  3                     11          0   
2  94103.0       B03                  3                     10          0   
3      NaN       B04                  3                     10          0   
4  94109.0       B04                  2                      9          0   

   EMS Personnel  Fire Fatalities  Fire Injuries  Civilian Fatalities  \
0              0                0              0                    0   
1              0                0              0                    0   
2              0                0              0                    0   
3              0                0              0                    0   
4              0                0              0                    0   

   Civilian Injuries  Weekday  Hour  Month  
0                  0        6    18      4  
1                  0        3    10      7  
2                  0        6     3      5  
3                  0        1    16      4  
4                  0        1    18     11

In [65]:
#df_X2['Estimated Property Loss'].min()

In [66]:
#df_X2['Estimated Property Loss'] = df_X2['Estimated Property Loss'].apply(lambda x : x if  x > 0 else 0 )

In [67]:
#df_X2['Estimated Property Loss'].min()

In [68]:
# Create dataset
#imputed = pd.DataFrame()

# Fill missing values of Age with the average of Age (mean)
#imputed[ 'Estimated Property Loss' ] = df_X2['Estimated Property Loss'].fillna( df_X2['Estimated Property Loss'].mean() )

In [69]:
#imputed[ 'Estimated Property Loss' ] = df_X2['Estimated Property Loss'].fillna( df_X2['Estimated Property Loss'].mean() )

In [70]:
#imputed[ 'Estimated Property Loss' ].min()

In [71]:
#df_X2['Estimated Contents Loss'].min()

In [72]:
#df_X2['Estimated Contents Loss'] = df_X2['Estimated Contents Loss'].apply(lambda x : x if  x > 0 else 0 )

In [73]:
#df_X2['Estimated Contents Loss'].min()

In [74]:
#imputed[ 'Estimated Contents Loss' ] = df_X2['Estimated Contents Loss'].fillna( df_X2['Estimated Contents Loss'].mean() )

In [75]:
#imputed[ 'Estimated Contents Loss' ]

In [76]:
#! pip install impyute

In [77]:
# from impyute.imputation.cs import mice

# # start the MICE training
# imputed_training=mice(df_X2['Estimated Property Loss'].values)

In [78]:
#df_X2[ 'Detector Alerted Occupants'][:500]

In [79]:
#imputed[ 'Estimated Property Loss' ] = df_X2['Estimated Property Loss'].fillna( df_X2['Estimated Property Loss']

In [80]:
# df_X2 = df_X2[df_X2.Zipcode != 'Nan']
# df_X2.where(filter1,inplace=True)

In [81]:
df_X2 = df_X2[pd.notnull(df_X2['Zipcode'])]

In [82]:
df_X2.shape

(266535, 13)

In [83]:
df_X2.head(10)

Zipcode Battalion  Suppression Units  Suppression Personnel  EMS Units  \
2   94103.0       B03                  3                     10          0   
4   94109.0       B04                  2                      9          0   
5   94123.0       B04                  3                     11          0   
6   94134.0       B10                  1                      4          0   
7   94122.0       B08                  8                     28          1   
8   94107.0       B10                  3                     10          0   
9   94107.0       B10                  1                      4          0   
10  94118.0       B07                  3                     10          0   
11  94105.0       B03                  3                     10          0   
12  94133.0       B01                  2                      9          0   

    EMS Personnel  Fire Fatalities  Fire Injuries  Civilian Fatalities  \
2               0                0              0                    0   
4               0                0              0                    0   
5               0                0              0                    0   
6               0                0              0                    0   
7               2                0              0                    0   
8               0                0              0                    0   
9               0                0              0                    0   
10              0                0              0                    0   
11              0                0              0                    0   
12              0                0              0                    0   

    Civilian Injuries  Weekday  Hour  Month  
2                   0        6     3      5  
4                   0        1    18     11  
5                   0        2     8      8  
6                   0        3    13      3  
7                   0        5     2      6  
8                   0        6    17     10  
9                   0        3    17      4  
10                  0        5     7     11  
11                  0        6    11      1  
12                  0        4    20      2

In [84]:
df_X2['Battalion'].unique()
df_X2['Battalion'] = pd.Categorical(df_X2['Battalion'])
one_hot = pd.get_dummies(df_X2['Battalion'],prefix='Battalion')
#df_X2 = df_X2.drop('Battalion',axis = 1)
# Join the encoded df
df_X2 = df_X2.join(one_hot)
df_X2.head(10)

Zipcode Battalion  Suppression Units  Suppression Personnel  EMS Units  \
2   94103.0       B03                  3                     10          0   
4   94109.0       B04                  2                      9          0   
5   94123.0       B04                  3                     11          0   
6   94134.0       B10                  1                      4          0   
7   94122.0       B08                  8                     28          1   
8   94107.0       B10                  3                     10          0   
9   94107.0       B10                  1                      4          0   
10  94118.0       B07                  3                     10          0   
11  94105.0       B03                  3                     10          0   
12  94133.0       B01                  2                      9          0   

    EMS Personnel  Fire Fatalities  Fire Injuries  Civilian Fatalities  \
2               0                0              0                    0   
4               0                0              0                    0   
5               0                0              0                    0   
6               0                0              0                    0   
7               2                0              0                    0   
8               0                0              0                    0   
9               0                0              0                    0   
10              0                0              0                    0   
11              0                0              0                    0   
12              0                0              0                    0   

    Civilian Injuries  ...  Battalion_B02  Battalion_B03  Battalion_B04  \
2                   0  ...              0              1              0   
4                   0  ...              0              0              1   
5                   0  ...              0              0              1   
6                   0  ...              0              0              0   
7                   0  ...              0              0              0   
8                   0  ...              0              0              0   
9                   0  ...              0              0              0   
10                  0  ...              0              0              0   
11                  0  ...              0              1              0   
12                  0  ...              0              0              0   

    Battalion_B05  Battalion_B06  Battalion_B07  Battalion_B08  Battalion_B09  \
2               0              0              0              0              0   
4               0              0              0              0              0   
5               0              0              0              0              0   
6               0              0              0              0              0   
7               0              0              0              1              0   
8               0              0              0              0              0   
9               0              0              0              0              0   
10              0              0              1              0              0   
11              0              0              0              0              0   
12              0              0              0              0              0   

    Battalion_B10  Battalion_B99  
2               0              0  
4               0              0  
5               0              0  
6               1              0  
7               0              0  
8               1              0  
9               1              0  
10              0              0  
11              0              0  
12              0              0  

[10 rows x 24 columns]

In [85]:
df_X2['Zipcode'].unique()
df_X2['Zipcode'] = pd.Categorical(df_X2['Zipcode'])
one_hot = pd.get_dummies(df_X2['Zipcode'],prefix='Zipcode')
#df_X2 = df_X2.drop('Battalion',axis = 1)
# Join the encoded df
df_X2 = df_X2.join(one_hot)

In [86]:
df_X2.head(10)

Zipcode Battalion  Suppression Units  Suppression Personnel  EMS Units  \
2   94103.0       B03                  3                     10          0   
4   94109.0       B04                  2                      9          0   
5   94123.0       B04                  3                     11          0   
6   94134.0       B10                  1                      4          0   
7   94122.0       B08                  8                     28          1   
8   94107.0       B10                  3                     10          0   
9   94107.0       B10                  1                      4          0   
10  94118.0       B07                  3                     10          0   
11  94105.0       B03                  3                     10          0   
12  94133.0       B01                  2                      9          0   

    EMS Personnel  Fire Fatalities  Fire Injuries  Civilian Fatalities  \
2               0                0              0                    0   
4               0                0              0                    0   
5               0                0              0                    0   
6               0                0              0                    0   
7               2                0              0                    0   
8               0                0              0                    0   
9               0                0              0                    0   
10              0                0              0                    0   
11              0                0              0                    0   
12              0                0              0                    0   

    Civilian Injuries  ...  Zipcode_94123.0  Zipcode_94124.0  Zipcode_94127.0  \
2                   0  ...                0                0                0   
4                   0  ...                0                0                0   
5                   0  ...                1                0                0   
6                   0  ...                0                0                0   
7                   0  ...                0                0                0   
8                   0  ...                0                0                0   
9                   0  ...                0                0                0   
10                  0  ...                0                0                0   
11                  0  ...                0                0                0   
12                  0  ...                0                0                0   

    Zipcode_94129.0  Zipcode_94130.0  Zipcode_94131.0  Zipcode_94132.0  \
2                 0                0                0                0   
4                 0                0                0                0   
5                 0                0                0                0   
6                 0                0                0                0   
7                 0                0                0                0   
8                 0                0                0                0   
9                 0                0                0                0   
10                0                0                0                0   
11                0                0                0                0   
12                0                0                0                0   

    Zipcode_94133.0  Zipcode_94134.0  Zipcode_94158.0  
2                 0                0                0  
4                 0                0                0  
5                 0                0                0  
6                 0                1                0  
7                 0                0                0  
8                 0                0                0  
9                 0                0                0  
10                0                0                0  
11                0                0                0  
12                1                0                0  

[10 ro

In [87]:
list(df_X2)

['Zipcode',
 'Battalion',
 'Suppression Units',
 'Suppression Personnel',
 'EMS Units',
 'EMS Personnel',
 'Fire Fatalities',
 'Fire Injuries',
 'Civilian Fatalities',
 'Civilian Injuries',
 'Weekday',
 'Hour',
 'Month',
 'Battalion_B01',
 'Battalion_B02',
 'Battalion_B03',
 'Battalion_B04',
 'Battalion_B05',
 'Battalion_B06',
 'Battalion_B07',
 'Battalion_B08',
 'Battalion_B09',
 'Battalion_B10',
 'Battalion_B99',
 'Zipcode_94102.0',
 'Zipcode_94103.0',
 'Zipcode_94104.0',
 'Zipcode_94105.0',
 'Zipcode_94107.0',
 'Zipcode_94108.0',
 'Zipcode_94109.0',
 'Zipcode_94110.0',
 'Zipcode_94111.0',
 'Zipcode_94112.0',
 'Zipcode_94114.0',
 'Zipcode_94115.0',
 'Zipcode_94116.0',
 'Zipcode_94117.0',
 'Zipcode_94118.0',
 'Zipcode_94121.0',
 'Zipcode_94122.0',
 'Zipcode_94123.0',
 'Zipcode_94124.0',
 'Zipcode_94127.0',
 'Zipcode_94129.0',
 'Zipcode_94130.0',
 'Zipcode_94131.0',
 'Zipcode_94132.0',
 'Zipcode_94133.0',
 'Zipcode_94134.0',
 'Zipcode_94158.0']

In [88]:
df_y = df_X2['Suppression Personnel']

In [89]:
df_y

2         10
4          9
5         11
6          4
7         28
8         10
9          4
10        10
11        10
12         9
13        11
17         5
18         9
19         9
20        33
21        12
22         9
23        10
24         4
25         4
26         6
27         9
29        10
30         9
31        11
32        10
33         4
34        30
35         3
36         4
          ..
490488     5
490489     5
490496     4
490497    29
490499    11
490501    11
490503    11
490504    10
490507    10
490509    28
490511     4
490512     5
490514     5
490515     5
490519    10
490521     4
490523     5
490525     5
490526    15
490527    11
490528    15
490534    19
490538    16
490544     4
490546     5
490550     4
490551    10
490553    19
490554    10
490555    33
Name: Suppression Personnel, Length: 266535, dtype: int64

In [90]:
df_feature  = df_X2.drop(['Suppression Personnel','Battalion','Zipcode'],axis=1)

In [91]:
df_feature.head(10)

Suppression Units  EMS Units  EMS Personnel  Fire Fatalities  \
2                   3          0              0                0   
4                   2          0              0                0   
5                   3          0              0                0   
6                   1          0              0                0   
7                   8          1              2                0   
8                   3          0              0                0   
9                   1          0              0                0   
10                  3          0              0                0   
11                  3          0              0                0   
12                  2          0              0                0   

    Fire Injuries  Civilian Fatalities  Civilian Injuries  Weekday  Hour  \
2               0                    0                  0        6     3   
4               0                    0                  0        1    18   
5               0                    0                  0        2     8   
6               0                    0                  0        3    13   
7               0                    0                  0        5     2   
8               0                    0                  0        6    17   
9               0                    0                  0        3    17   
10              0                    0                  0        5     7   
11              0                    0                  0        6    11   
12              0                    0                  0        4    20   

    Month  ...  Zipcode_94123.0  Zipcode_94124.0  Zipcode_94127.0  \
2       5  ...                0                0                0   
4      11  ...                0                0                0   
5       8  ...                1                0                0   
6       3  ...                0                0                0   
7       6  ...                0                0                0   
8      10  ...                0                0                0   
9       4  ...                0                0                0   
10     11  ...                0                0                0   
11      1  ...                0                0                0   
12      2  ...                0                0                0   

    Zipcode_94129.0  Zipcode_94130.0  Zipcode_94131.0  Zipcode_94132.0  \
2                 0                0                0                0   
4                 0                0                0                0   
5                 0                0                0                0   
6                 0                0                0                0   
7                 0                0                0                0   
8                 0                0                0                0   
9                 0                0                0                0   
10                0                0                0                0   
11                0                0                0                0   
12                0                0                0                0   

    Zipcode_94133.0  Zipcode_94134.0  Zipcode_94158.0  
2                 0                0                0  
4                 0                0                0  
5                 0                0                0  
6                 0                1                0  
7                 0                0                0  
8                 0                0                0  
9                 0                0                0  
10                0                0                0  
11                0                0                0  
12                1                0                0  

[10 rows x 48 columns]

In [92]:
df_feature.shape

(266535, 48)

In [123]:
def preprocessInput(read_df):
    df_X = read_df.drop(['Number of Alarms', 'Number of floors with minimum damage', 'Number of floors with significant damage', 'Ignition Cause', 'Number of floors with heavy damage', 'Number of floors with extreme damage', 'Detector Failure Reason', 'Number of Sprinkler Heads Operating', 'Item First Ignited', 'Automatic Extinguishing Sytem Type', 'Automatic Extinguishing Sytem Perfomance', 'Automatic Extinguishing Sytem Failure Reason', 'Supervisor District', 'Neighborhood  District'  ], axis = 1)
    df_X1 = df_X.drop(['Human Factors Associated with Ignition','Arrival DtTm', 'Close DtTm', 'No Flame Spead', 'Mutual Aid','City','Fire Spread','Detector Type','Detector Operation','Detector Effectiveness', 'Primary Situation', 'Other Units'
 ,'Other Personnel', 'Action Taken Other', 'Action Taken Secondary', 'First Unit On Scene', 'Call Number','Station Area' ], axis=1)
    df_X1['Weekday'] = df_X1['Alarm DtTm'].apply(lambda x: convert_date_to_weekday(x))
    df_X1['Hour'] = df_X1['Alarm DtTm'].apply(lambda x: convert_date_to_hour(x))
    df_X1['Month'] = df_X1['Alarm DtTm'].apply(lambda x: convert_date_to_month(x))
    df_X2 = df_X1.drop(['Exposure Number','Location', 'Ignition Factor Secondary', 'Heat Source','Floor of Fire Origin','Box' ,'Structure Status','Alarm DtTm', 'Area of Fire Origin', 'Incident Date', 'Incident Number', 'Action Taken Primary','Ignition Factor Primary', 'Structure Type', 'Automatic Extinguishing System Present','Detectors Present','Property Use','Estimated Property Loss','Estimated Contents Loss', 'Detector Alerted Occupants', 'Address'], axis=1)
    df_X2['Battalion'].unique()
    df_X2['Battalion'] = pd.Categorical(df_X2['Battalion'])
    one_hot = pd.get_dummies(df_X2['Battalion'],prefix='Battalion')
    #df_X2 = df_X2.drop('Battalion',axis = 1)
    # Join the encoded df
    df_X2 = df_X2.join(one_hot)
    df_X2['Zipcode'] = pd.Categorical(df_X2['Zipcode'])
    one_hot = pd.get_dummies(df_X2['Zipcode'],prefix='Zipcode')
    #df_X2 = df_X2.drop('Battalion',axis = 1)
    # Join the encoded df
    df_X2 = df_X2.join(one_hot)
    df_feature  = df_X2.drop(['Battalion','Zipcode'],axis=1)
    return df_feature

In [125]:
read_df = pd.read_csv('Fire_Incidents.tsv', sep='\t')
df_feature = preprocessInput(read_df)
df_feature = df_feature.drop_duplicates()
df_y = df_feature['Suppression Personnel']
df_feature = df_feature.drop(['Suppression Personnel'],axis=1)


In [ ]:
from sklearn.model_selection import train_test_split
df_feature_train, df_feature_test, df_y_train, df_y_test = train_test_split(df_feature, df_y, test_size = 0.2, random_state = 0)

In [126]:
df_feature_train.shape

(254804, 48)

In [127]:
df_feature_test.shape

(63702, 48)

In [128]:
from sklearn.preprocessing import StandardScaler

In [129]:
sc_X = StandardScaler()
X_train = sc_X.fit_transform(df_feature_train)
X_test = sc_X.fit_transform(df_feature_test)
sc_y = StandardScaler()


C:\Users\Rutul Thakkar\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype uint8, int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Rutul Thakkar\Anaconda3\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype uint8, int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Users\Rutul Thakkar\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype uint8, int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Rutul Thakkar\Anaconda3\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype uint8, int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [130]:
X_train[:10]

array([[ 1.68819917e-02, -2.70184611e-01, -3.53404808e-01,
        -1.98106047e-03, -1.49344410e-02, -7.97385241e-03,
        -2.50564669e-02, -1.01390258e+00,  1.29093471e+00,
         4.28267399e-01, -3.94567816e-01, -3.93830199e-01,
        -4.01112399e-01,  3.02535407e+00, -3.02681951e-01,
        -2.81331722e-01, -2.52458821e-01, -3.10920779e-01,
        -3.14829226e-01, -3.09879758e-01, -1.04471868e-01,
        -2.94173227e-01, -2.84398504e-01, -1.12918555e-01,
        -1.70804831e-01, -2.08659537e-01, -1.65686619e-01,
        -2.79018099e-01, -2.61980737e-01, -1.48047124e-01,
        -1.79400012e-01, -1.93356842e-01,  4.64424365e+00,
        -1.22811171e-01, -1.83781656e-01, -1.65724123e-01,
        -1.39076952e-01, -1.68786420e-01, -1.57869471e-01,
        -1.80562069e-01, -9.89778619e-02, -7.56519485e-02,
        -5.96695640e-02, -1.48558468e-01, -1.66522410e-01,
        -1.71133105e-01, -1.54414293e-01, -8.54729101e-02],
       [-6.83015602e-02, -2.70184611e-01, -3.53404808e-

In [131]:
# from sklearn.preprocessing import OneHotEncoder

In [132]:
# enc = OneHotEncoder()

In [133]:
# enc.fit(df_feature)


In [134]:
# onehotlabels = enc.transform(df_feature)

In [135]:
# onehotlabels.shape

In [136]:
# from scipy.sparse import csr_matrix

# def dataframetoCSRmatrix(df):
#     nrows = len(df)
#     nc = len(df.columns)
#     idx = {}
#     tid = 0
#     nnz = nc * nrows
    
#     cols= df.columns
    
#     for col in cols:
#         df[col] = df[col].apply(str)
#         for name in df[col].unique():
#             idx[col+name] = tid
#             tid += 1
    
#     ncols = len(idx)
    
#     ind = np.zeros(nnz, dtype=np.int)
#     val = np.zeros(nnz, dtype=np.int)
#     ptr = np.zeros(nrows+1, dtype=np.int)
    
#     i=0
#     n=0
    
#     for index,row in df.iterrows():
#         for j,col in enumerate(cols):
#             ind[j+n] = idx[col+row[col]]
#             val[j+n] = 1
#         ptr[i+1] = ptr[i] + nc
#         n += nc
#         i += 1
    
#     mat = csr_matrix((val,ind,ptr), shape=(nrows,ncols), dtype=np.int)
#     mat.sort_indices()   
    
#     return mat
    


In [137]:
# mat_train = dataframetoCSRmatrix(df_feature)

# print("Shape of CSR Matrix -", mat.shape)

In [138]:
# mat_test = dataframetoCSRmatrix(df_feature)

In [139]:
from sklearn.ensemble import RandomForestClassifier

rfclf = RandomForestClassifier(max_depth=1, random_state=42)
rfclf.fit(X_train, df_y_train)

from sklearn.metrics import f1_score

predicted_y = rfclf.predict(X_test)
print("test accuracy: ",f1_score(df_y_test, predicted_y, average='micro'))

C:\Users\Rutul Thakkar\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


test accuracy:  0.2867884838780572


In [121]:
from sklearn.externals import joblib 
  

In [122]:
joblib.dump(rfclf, 'sf.pkl') 

['sf.pkl']